#Paths
vanilla: False
data_path: "generated_data/"
env_path: "v3/"
vanilla_path: "Peschl/"
expe_path: "expert"
demo_path: "demonstrations"
disc_path: "discriminator"
gene_path: "generator"
gene: "_gene"
moral_path: "moral_agents/"
model_ext: ".pt"
demo_ext: ".pk"
model_name: "ppo_"


# Editable parameters
direct_filename: True
moral_agent: False # True if moral_agent, False if PPO basic agent

agent_filename: "generated_data/v5/[0, 0, 1, 1]/expert.pt"
# agent_filename: "generated_data/v3/moral_agents/[[0, 1, 0, 1], [0, 0, 1, 1]]131_new_norm_v6_v3_after_queries_fixed.pt"
# agent_filename: "generated_data/v3/rand/expert.pt"
# agent_filename: "generated_data/v3/[1, 0, 0, 0]/expert.pt"
# agent_filename: "generated_data/v3/[0, 1, 0, 1]/expert.pt"
# agent_filename: "generated_data/v3/[0, 0, 1, 1]/expert.pt"

demos_filename: "generated_data/v5/[0, 0, 1, 1]/demonstrations.pk"
# demos_filename: "generated_data/v3/rand/demonstrations.pk"
# demos_filename: "generated_data/v3/moral_agents/DEMOS_[[0, 1, 0, 1], [0, 0, 1, 1]]131_new_norm_v6_v3_after_queries_fixed.pk"

# demos_filename: "generated_data/v3/demo_batch/[[0, 1, 0, 1], [0, 0, 1, 1]]131.pk"
# demos_filename: "generated_data/v3/demo_batch/rand.pk"
# demos_filename: "generated_data/v3/demo_batch/[1, 0, 0, 0].pk"
# demos_filename: "generated_data/v3/demo_batch/[0, 1, 0, 1].pk"
# demos_filename: "generated_data/v3/demo_batch/[0, 0, 1, 1].pk"



n_workers: 12
gamma: 0.999
eth_norm: "v6"
non_eth_norm: "v3"
rand: "rand/"
non_eth_experts_weights: [1,0,0,0]

env: "v3"
env_rad: "randomized_"
#nb_experts: 1
experts_weights: [[0,1,0,1], [0,0,1,1]]
nb_experts: 1
# experts_weights: [[0,1]]
geneORexpert: 0 # 0 for generator and 1 for expert, using ppo agent to calculate utopia during the moral process


#######
# Peschl Values #
#######
nb_demos: 2000

#######
# Test Values #
#######
# nb_demos: 100
