#Paths
real_params: True
vanilla: False
data_path: "generated_data/"
vanilla_path: "Peschl/"
expe_path: "expert"
demo_path: "demonstrations"
disc_path: "discriminator"
gene_path: "generator"
moral_path: "moral_agents/"
model_ext: ".pt"
demo_ext: ".pk"
model_name: "ppo_"
special_name_agent: "1111_norm_v6_v3"

# new stuff about normalization
rand: "rand/"
non_eth_experts_weights: [1,0,0,0]


# Editable parameters
env: "v3"
env_rad: "randomized_"
nb_experts: 2
# experts_weights: [[0,1]]
experts_weights: [[0,1,0,1],[0,0,1,1]]
# experts_weights: [[0,1,0,0],[0,0,1,0],[0,0,1,1]]
# experts_weights: [[0,1,1,1]]
# ratio: [1, 1]
ratio: [1, 3, 1]
# ratio: [1, 1, 1, 1]
geneORexpert: 0 # 0 for generator and 1 for expert, using ppo agent to calculate utopia during the moral process
normalization_eth_sett: "v6"
normalization_non_eth_sett: "v3"

# pref
n_queries: 200
nb_query_test: 20
# query_selection: "compare_EUS"
# query_selection: "compare_MORAL"
# query_selection: "compare_EUS"
query_selection: "random"
posterior_mode: "moral"
prop_w_mode: "basic_temperature"
# prop_w_mode: "moral"
temperature_mcmc: 2
n_workers: 2
batchsize_ppo: 2
gamma: 0.999
dimension_pref: 3
agent_test_name: "generated_data/v3/moral_agents/[[0, 1, 0, 1], [0, 0, 1, 1]]131_new_norm_v6_v3_after_queries_fixed.pt"


#######
# Peschl Values #
#######
env_steps: 8000000
#### query_freq: 153 846 # env_steps_moral/(n_queries+2)
