#Paths
real_params: True
vanilla: False
data_path: "generated_data/"
env_path: "v3/"
vanilla_path: "Peschl/"
expe_path: "expert"
demo_path: "demonstrations"
disc_path: "discriminator"
gene_path: "generator"
moral_path: "moral_agents/"
model_ext: ".pt"
demo_ext: ".pk"
model_name: "ppo_"
special_name_agent: "old_settings_131_test_curves"


# Editable parameters
env: "v3"
env_rad: "randomized_"
experts: 2
# experts_weights: [[0,1]]
# ratio: [1,1]
experts_weights: [[0,1,0,1],[0,0,1,1]]
ratio: [1, 3, 1]
geneORexpert: 0 # 0 for generator and 1 for expert, using ppo agent to calculate utopia during the moral process


#######
# Peschl Values #
#######
env_steps: 8000000
n_queries: 50
#### query_freq: 153 846 # env_steps_moral/(n_queries+2)


#######
# Test Values #
#######
#env_steps: 100
#n_queries: 2
query_freq: 99

#######
# Test Queries Values #
#######
#env_steps: 10000
#n_queries: 2
#query_freq: 500
