#Paths
real_params: True
vanilla: False
data_path: "generated_data/"
vanilla_path: "Peschl/"
expe_path: "expert"
demo_path: "demonstrations"
disc_path: "discriminator"
gene_path: "generator"
moral_path: "moral_agents/"
model_ext: ".pt"
demo_ext: ".pk"
model_name: "ppo_"

# Editable parameters
env: "v3"
env_rad: "randomized_"
env_id: "randomized_v3"
nb_experts: 2
# experts_weights: [[0,1]]
experts_weights: [[0,1,0,1],[0,0,1,1]]
# experts_weights: [[0,1,0,0],[0,0,1,0],[0,0,0,1]]
# experts_weights: [[0,1,0,0],[0,0,1,0],[0,0,0,1],[0,1,0,1],[0,0,1,1],[0,1,1,1]]
# experts_weights: [[0,1,1,1]]
# ratio: [1, 1]
ratio: [1, 1, 1]
# ratio: [1, 1, 1, 1]
# ratio: [1, 1, 1, 1, 1, 1, 1]
# special_name_agent: "T3_marius_prior_conv01_norm_v6_v3"
special_name_agent: "Test_moral_2"

# PPO
batchsize_ppo_phase_1: 120
batchsize_ppo_phase_2: 12
n_queries: 2
preference_noise: 0
n_workers: 12
lr_ppo: 0.0003
entropy_reg: 0.25
gamma: 0.999
epsilon: 0.1
ppo_epochs: 5
env_steps: 8000000
# env_steps: 16000000

# NORMALIZATION
eth_norm: "v6"
non_eth_norm: "v3"
geneORexpert: 0 # 0 for generator and 1 for expert, using ppo agent to calculate utopia during the moral process
non_eth_experts_weights: [1,0,0,0]
test: False
n_best: 100

# PREFERENCES
n_queries: 200
query_freq: 99 # not real value if real_params = True
pref_giver_no_null: True
temperature_mcmc : 10
cov_range: 0.01
nb_query_test: 1
nb_mcmc: 1
demos_filename: "generated_data/v3/moral_agents/DEMOS_[[0, 1, 0, 1], [0, 0, 1, 1]]131_new_norm_v6_v3_after_queries_fixed.pk"

# query_selection: "compare_EUS"
# query_selection: "compare_MORAL"
# query_selection: "compare_basic_log_lik"
# query_selection: "random"
# query_selection: "random_no_double_null"
query_selection: "random_less_null"

# posterior_mode: "print"
# posterior_mode: "moral"
# posterior_mode: "basic"
posterior_mode: "basic_temperature"

# prop_w_mode: "moral"
prop_w_mode: "normalized_linalg_positive"

# prior: "marius"
prior: "marius_2"
# prior: "moral"

# mcmc_type: successive
mcmc_type: parallel
# mcmc_type: concat