#Paths
real_params: True
vanilla: False
data_path: "generated_data/"
vanilla_path: "Peschl/"
expe_path: "expert"
demo_path: "demonstrations"
disc_path: "discriminator"
gene_path: "generator"
moral_path: "moral_agents/"
model_ext: ".pt"
demo_ext: ".pk"
model_name: "ppo_"
# special_name_agent: "T3_marius_prior_conv01_norm_v6_v3"
special_name_agent: "Q_on_ACTIONS_from_scratch_T3_marius_prior_conv01_norm_v6_v3"


# Editable parameters
env: "v3"
env_rad: "randomized_"
env_id: "randomized_v3"
nb_experts: 2
# experts_weights: [[0,1]]
experts_weights: [[0,1,0,1],[0,0,1,1]]
# experts_weights: [[0,1,0,0],[0,0,1,0],[0,0,0,1]]
# experts_weights: [[0,1,0,0],[0,0,1,0],[0,0,0,1],[0,1,0,1],[0,0,1,1],[0,1,1,1]]
# experts_weights: [[0,1,1,1]]
# ratio: [1, 1]
ratio: [1, 3, 1]
# ratio: [1, 1, 1, 1]
# ratio: [1, 1, 1, 1, 1, 1, 1]
geneORexpert: 0 # 0 for generator and 1 for expert, using ppo agent to calculate utopia during the moral process

# new stuff about normalization
rand: "rand/"
non_eth_experts_weights: [1,0,0,0]

# PPO
batchsize_ppo: 12
n_queries: 2
preference_noise: 0
n_workers: 12
lr_ppo: 0.0003
entropy_reg: 0.25
gamma: 0.999
epsilon: 0.1
ppo_epochs: 5
eth_norm: "v6"
non_eth_norm: "v3"
test: True

# PREFERENCES
pref_giver_no_null: True
temperature_mcmc : 3
cov_range: 0.1
prop_w_mode: "moral"
nb_query_test: 1

posterior_mode : "basic_temperature"

prior: "marius"
# prior: "marius_2"
# prior: "moral"

# query_selection: "compare_EUS"
# query_selection: "compare_MORAL"
query_selection: "compare_basic_log_lik"
# query_selection: "random"
# query_selection: "random_no_double_null"
# query_selection: "random_less_null"


#######
# Peschl Values #
#######
env_steps: 8000000
n_queries: 50
# n_queries: 200
#### query_freq: 153 846 # env_steps_moral/(n_queries+2)


#######
# Test Values #
#######
# env_steps: 100
# n_queries: 2
query_freq: 99

#######
# Test Queries Values #
#######
# env_steps: 10000
# n_queries: 2
# query_freq: 150

