#Paths
vanilla: False
data_path: "generated_data/"
# env_path: "v3/"
env_path: "v5/"
vanilla_path: "Peschl/"
expe_path: "expert"
demo_path: "demonstrations"
disc_path: "discriminator"
gene_path: "generator"
moral_path: "moral_agents/"
model_ext: ".pt"
demo_ext: ".pk"
model_name: "ppo_"

# params
batchsize_discriminator: 512
batchsize_ppo: 12
n_workers: 12 
entropy_reg: 0
gamma: 0.999
epsilon: 0.1
ppo_epochs: 5

# Editable parameters
# env: "v3"
# env_rad: "randomized_"
# env_id: "randomized_v3"
env: "v5"
env_rad: "randomized_"
env_id: "randomized_v5"
expert_weights: [0,0,1,1]

#######
# Peschl Values #
#######
env_steps: 6000000

#######
# Test Values #
#######
# env_steps: 1000
