#Paths
real_params: True
vanilla: False
data_path: "generated_data/"
vanilla_path: "Peschl/"
expe_path: "expert"
demo_path: "demonstrations"
disc_path: "discriminator"
gene_path: "generator"
moral_path: "moral_agents/"
model_ext: ".pt"
demo_ext: ".pk"
model_name: "ppo_"
special_name_agent: "131_norm_v6_v3"

# new stuff about normalization
rand: "rand/"
non_eth_experts_weights: [1,0,0,0]


# Editable parameters
env: "v3"
env_rad: "randomized_"
env_id: "randomized_v3"
nb_experts: 2
# experts_weights: [[0,1]]
experts_weights: [[0,1,0,1],[0,0,1,1]]
# experts_weights: [[0,1,0,0],[0,0,1,0],[0,0,1,1]]
# experts_weights: [[0,1,1,1]]
# ratio: [1, 1]
ratio: [3, 1, 1]
# ratio: [1, 1, 1, 1]
geneORexpert: 0 # 0 for generator and 1 for expert, using ppo agent to calculate utopia during the moral process
normalization_eth_sett: "v6"
normalization_non_eth_sett: "v3"
# normalization_eth_sett: "v1"
# normalization_non_eth_sett: "v6"
n_best: 100

# pref
n_queries: 50
nb_query_test: 20
pref_giver_no_null: True
Q_on_actions: False

# query_selection: "compare_EUS"
# query_selection: "compare_EUS_less_zeros"
# query_selection: "compare_MORAL"
# query_selection: "compare_MORAL_less_zeros"
query_selection: "compare_basic_log_lik"
# query_selection: "compare_basic_log_lik_less_zeros"
# query_selection: "random"
# query_selection: "random_no_double_null"
# query_selection: "random_less_null"

# posterior_mode: "print"
# posterior_mode: "moral"
# posterior_mode: "basic"
posterior_mode: "basic_temperature"

# prop_w_mode: "moral"
prop_w_mode: "normalized_linalg_positive"

# mcmc_type: successive
mcmc_type: parallel
# mcmc_type: concat

# prior: "marius"
prior: "marius_2"
# prior: "moral"

# mcmc_log: final
mcmc_log: active
temperature_mcmc: 10
# cov_range: 1
cov_range: 0.01
nb_mcmc: 1
dimension_pref: 3

test: False
n_workers: 12
batchsize_ppo: 120
gamma: 0.999

agent_test_name: "generated_data/v3/moral_agents/[[0, 1, 0, 1], [0, 0, 1, 1]]131_new_norm_v6_v3_after_queries_fixed.pt"


# demos_filename: "generated_data/v3/moral_agents/DEMOS_[[0, 1, 0, 1], [0, 0, 1, 1]]131_new_norm_v6_v3_after_queries_fixed.pk"
# demos_filename: "generated_data/v3/rand/demonstrations.pk"

batch_path: "generated_data/v3/demo_batch"


#######
# Peschl Values #
#######
env_steps: 8000000
# env_steps: 16000000
#### query_freq: 153 846 # env_steps_moral/(n_queries+2)
